from django.urls import path, include
from .import views
from rest_framework.routers import DefaultRouter


#creating router for using viewSet or viewModelSet
router = DefaultRouter()  # creating object
router.register('emp', views.EmployeeViewSet, basename='employee')  # basename only used when we are using viewSet in the view.py other wise it is autogenerated

urlpatterns = [
    # path("", views.Employees.as_view(), name = "employees_list"),
    # path("<int:pk>/", views.EmployeesUpdate.as_view(), name = "employees_details"),

    path('', include(router.urls))
]