# Generated by Django 5.1.7 on 2025-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.IntegerField(),
        ),
    ]
